# Generated by Django 3.1.7 on 2021-04-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id']},
        ),
    ]
